{
    "_Type": "Action.Type.OfflineOData.Close",
    "Service": "/MDK_AssetInspection/Services/SampleServiceV2.service",
    "Force": true,
    "ActionResult": {
        "_Name": "close"
    },
    "OnSuccess": "/MDK_AssetInspection/Actions/Service/CloseOfflineSuccessMessage.action",
    "OnFailure": "/MDK_AssetInspection/Actions/Service/CloseOfflineFailureMessage.action"
}