{
    "Service": "/MDK_AssetInspection/Services/SampleServiceV2.service",
    "DefiningRequests": [{
        "Name": "Customers",
        "Query": "Customers"
    }],
    "_Type": "Action.Type.ODataService.Initialize",
    "ShowActivityIndicator": true,
    "ActivityIndicatorText": "Downloading...",
    "ActionResult": {
        "_Name": "init"
    },
    "OnSuccess": "/MDK_AssetInspection/Actions/Service/InitializeOfflineSuccessMessage.action",
    "OnFailure": "/MDK_AssetInspection/Actions/Service/InitializeOfflineFailureMessage.action"
}