{
    "Service": "/MDK_MeterInformation/Services/SampleServiceV2.service",
    "DefiningRequests": [{
            "Name": "Customers",
            "Query": "Customers"
        },
        {
            "Name": "Products",
            "Query": "Products"
        },
        {
            "Name": "PurchaseOrderHeaders",
            "Query": "PurchaseOrderHeaders"
        },
        {
            "Name": "PurchaseOrderItems",
            "Query": "PurchaseOrderItems"
        },
        {
            "Name": "SalesOrderHeaders",
            "Query": "SalesOrderHeaders"
        }
    ],
    "_Type": "Action.Type.ODataService.Initialize",
    "ShowActivityIndicator": true,
    "ActivityIndicatorText": "Downloading...",
    "ActionResult": {
        "_Name": "init"
    },
    "OnSuccess": "/MDK_MeterInformation/Actions/Service/InitializeOfflineSuccessMessage.action",
    "OnFailure": "/MDK_MeterInformation/Actions/Service/InitializeOfflineFailureMessage.action"
}