{
	"_Type": "Action.Type.Navigation",
	"ActionResult": {
		"_Name": "NavToService_Order_Completion"
	},
	"PageToOpen": "/MDK_MeterInformation/Pages/Service_Order_Completion.page",
	"ModalPage": true
}